import { Inter } from "next/font/google";
import Link from "next/link";
import "./global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-normal">
        <nav className="flex items-center justify-between py-4 px-6">
          <div className="flex items-center">
            <Link href="">
              <svg
                width="35"
                height="35"
                viewBox="0 0 49 49"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M40.0469 12.0449L8.04687 12.0449"
                  stroke="#2D4768"
                  stroke-width="3"
                  stroke-linecap="round"
                />
                <path
                  d="M40.0469 24.0449L8.04687 24.0449"
                  stroke="#2D4768"
                  stroke-width="3"
                  stroke-linecap="round"
                />
                <path
                  d="M40.0469 36.0449H8.04687"
                  stroke="#2D4768"
                  stroke-width="3"
                  stroke-linecap="round"
                />
              </svg>
            </Link>
          </div>
          <div className="flex justify-center flex-1">
            <Link href="/" className="navLink mr-7">
              سياسة الخصوصية
            </Link>
            <Link href="/" className="navLink mr-7">
              أرقام التشغيل
            </Link>
            <Link href="/" className="navLink mr-7">
              الدعم الفني
            </Link>
            <Link href="/" className="navLink mr-7">
              اتصل بنا
            </Link>
            <Link href="/" className="navLink mr-7">
              من نحن
            </Link>
            <Link href="/" className="navLink mr-7">
              الرئيسية
            </Link>
          </div>
          <Link href="/">
            <img src="../../logo.png" alt="Logo" className="h-8" />
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
